<a href="https://colab.research.google.com/github/suyash091/DIGITS-EEG-DATASET-PREPARATION-TRADITIONAL-padded/blob/master/padding_preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Mount drive using PtcKing091@gmail.com

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive

In [0]:
#Get the dataset (run only first time)
!wget http://mindbigdata.com/opendb/MindBigData-EP-v1.0.zip

--2019-11-13 09:30:24--  http://mindbigdata.com/opendb/MindBigData-EP-v1.0.zip
Resolving mindbigdata.com (mindbigdata.com)... 86.109.162.167
Connecting to mindbigdata.com (mindbigdata.com)|86.109.162.167|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 427958689 (408M) [application/zip]
Saving to: ‘MindBigData-EP-v1.0.zip.1’

MindBigData-EP-v1.0 100%[===================>] 408.13M  1.18MB/s    in 4m 34s

2019-11-13 09:34:58 (1.49 MB/s) - ‘MindBigData-EP-v1.0.zip.1’ saved [427958689/427958689]

In [0]:
#extract the dataset, (run only first time)
!unzip /content/MindBigData-EP-v1.0.zip.1 #'/content/drive/My Drive/BCI MNIST'

Archive:  /content/MindBigData-EP-v1.0.zip.1
  inflating: EP1.01.txt

In [0]:
##imports
import gc
import pickle
import pandas as pd

In [0]:
#Remove unnecessary feature
import gc
def pop(ls):
  ls=ls.replace('\t',',').split(',')
  ls.pop(0)
  ls.pop(1)
  ls.pop(3)
  return ls

In [0]:
linestotal = [pop(line.rstrip('\n')) for line in open('/content/EP1.01.txt')]
gc.collect()

In [0]:
#since it is a big data problem, fragmenting into smaller pieces because all the data cannot fit into ram.
x=[(0,300000),(300000,600000),(60000,None)]
y=1
for i in x:
  lines=linestotal[i[0]:i[1]]
  with open('/content/drive/My Drive/BCI MNIST/outfile.'+str(y), 'wb') as fp:
    pickle.dump(lines, fp)
  y+=1
  lines=None
  gc.collect() #collect garbage to free up space

In [0]:
#Loading data file one at a time
with open ('/content/drive/My Drive/BCI MNIST/outfile.1', 'rb') as fp:
    itemlist = pickle.load(fp)

In [0]:
index=[ i[2] for i in itemlist ] #extracting predicted variable

In [0]:
#temp=67635
#tl=[]
#biglist=[]
#for i in itemlist:
#  if int(i[0])==temp:
#    tl+=i
#  else:
#    biglist.append(tl)
#    temp+=1
#   tl=i

In [0]:

#for i in range(temp,89064):
#  for j in ["AF3", "F7", "F3", "FC5", "T7", "P7", "O1", "O2", "P8", "T8", "FC6", "F4", "F8", "AF4"]:
#    for k in itemlist:
#      if k[0]==i and k[1]==j:
#        tl+=k
#  biglist.append(tl)
#  t1=[]
#biglist=[]
#def bigl(indices):
#  a=[]
#  for i in indices:
#    a=a+itemlist[i]
#  biglist.append(a)

In [0]:
#df.head(100)
#for i in range(67635,89064):
#  indices = [i for i, x in enumerate(index) if int(x) == i]
#  print(indices)
#  bigl(indices)

In [7]:
index[0:28]

['6',
 '6',
 '6',
 '6',
 '6',
 '6',
 '6',
 '6',
 '6',
 '6',
 '6',
 '6',
 '6',
 '6',
 '7',
 '7',
 '7',
 '7',
 '7',
 '7',
 '7',
 '7',
 '7',
 '7',
 '7',
 '7',
 '7',
 '7']

In [6]:
#removing incomplete data points
temp=index[0]
i=0
flag=False
while i <14:
  if index[i] !=  temp:
    flag=True
    break
  else:
    i+=1
if flag:
  index=index[i:]
  itemlist=itemlist[i:]
len(itemlist)

300000

In [10]:
[ itemlist[i].pop(0) for i in range(len(itemlist))] #run 3 times to remove unnecessary feature points

['6',
 '6',
 '6',
 '6',
 '6',
 '6',
 '6',
 '6',
 '6',
 '6',
 '6',
 '6',
 '6',
 '6',
 '7',
 '7',
 '7',
 '7',
 '7',
 '7',
 '7',
 '7',
 '7',
 '7',
 '7',
 '7',
 '7',
 '7',
 '9',
 '9',
 '9',
 '9',
 '9',
 '9',
 '9',
 '9',
 '9',
 '9',
 '9',
 '9',
 '9',
 '9',
 '9',
 '9',
 '9',
 '9',
 '9',
 '9',
 '9',
 '9',
 '9',
 '9',
 '9',
 '9',
 '9',
 '9',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '8',
 '8',
 '8',
 '8',
 '8',
 '8',
 '8',
 '8',
 '8',
 '8',
 '8',
 '8',
 '8',
 '8',
 '6',
 '6',
 '6',
 '6',
 '6',
 '6',
 '6',
 '6',
 '6',
 '6',
 '6',
 '6',
 '6',
 '6',
 '6',
 '6',
 '6',
 '6',
 '6',
 '6',
 '6',
 '6',
 '6',
 '6',
 '6',
 '6',
 '6',
 '6',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '6',
 '6',
 '6',
 '6',
 '6',
 '6',
 '6',
 '6',
 '6',
 '6',
 '6',
 '6',
 '6',
 '6',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '9',
 '9',
 '9',
 '9',
 '9',
 '9',
 '9',
 '9',
 '9',
 '9',
 '9',
 '9',
 '9',
 '9',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '8',
 '8',
 '8',
 '8',
 '8',
 '8',
 '8',
 '8',
 '8',
 '8',
 '8',
 '8',
 '8',
 '8',
 '9',
 '9',
 '9',
 '9',
 '9',
 '9',
 '9',
 '9',
 '9',
 '9',
 '9',
 '9',
 '9',
 '9',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '7',
 '7',
 '7',
 '7',
 '7',
 '7',
 '7',
 '7',
 '7',
 '7',
 '7',
 '7',
 '7',
 '7',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '7',
 '7',
 '7',
 '7',
 '7',
 '7',
 '7',
 '7',
 '7',
 '7',
 '7',
 '7',
 '7',
 '7',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '9',
 '9',
 '9',
 '9',
 '9',
 '9',
 '9',
 '9',
 '9',
 '9',
 '9',
 '9',
 '9',
 '9',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '6',
 '6',
 '6',
 '6',
 '6',
 '6',
 '6',
 '6',
 '6',
 '6',
 '6',
 '6',
 '6',
 '6',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '9',
 '9',
 '9',
 '9',
 '9',
 '9',
 '9',
 '9',
 '9',
 '9',
 '9',
 '9',
 '9',
 '9',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '7',
 '7',
 '7',
 '7',
 '7',
 '7',
 '7',
 '7',
 '7',
 '7',
 '7',
 '7',
 '7',
 '7',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '6',
 '6',
 '6',
 '6',
 '6',
 '6',
 '6',
 '6',
 '6',
 '6',
 '6',
 '6',
 '6',
 '6',
 '9',
 '9',
 '9',
 '9',
 '9',
 '9',
 '9',
 '9',
 '9',
 '9',
 '9',
 '9',
 '9',
 '9',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '7',
 '7',
 '7',
 '7',
 '7',
 '7',
 '7',
 '7',
 '7',
 '7',
 '7',
 '7',
 '7',
 '7',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '9',
 '9',
 '9',
 '9',
 '9',
 '9',
 '9',
 '9',
 '9',
 '9',
 '9',
 '9',
 '9',
 '9',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '4',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '0',
 '6',
 '6',
 '6',
 '6',
 '6',
 '6',
 '6',
 '6',
 '6',
 '6',
 '6',
 '6',
 '6',
 '6',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '8',
 '8',
 '8',
 '8',
 '8',
 '8',
 '8',
 '8',
 '8',
 '8',
 '8',
 '8',
 '8',
 '8',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '7',
 '7',
 '7',
 '7',
 '7',
 '7',
 '7',
 '7',
 '7',
 '7',
 '7',
 '7',
 '7',
 '7',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '1',
 '8',
 '8',
 '8',
 '8',
 '8',
 '8',
 '8',
 '8',
 '8',
 '8',
 '8',
 '8',
 '8',
 '8',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '2',
 '8',
 '8',
 '8',
 '8',
 '8',
 '8',
 '8',
 '8',
 '8',
 '8',
 '8',
 '8',
 '8',
 '8',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '8',
 '8',
 '8',
 '8',
 '8',
 '8',
 '8',
 '8',
 '8',
 '8',
 '8',
 '8',
 '8',
 '8',
 '8',
 '8',
 '8',
 '8',
 '8',
 '8',
 '8',
 '8',
 '8',
 '8',
 '8',
 '8',
 '8',
 '8',
 '8',
 '8',
 '8',
 '8',
 '8',
 '8',
 '8',
 '8',
 '8',
 '8',
 '8',
 '8',
 '8',
 '8',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '8',
 '8',
 '8',
 '8',
 '8',
 '8',
 '8',
 '8',
 '8',
 '8',
 '8',
 '8',
 '8',
 '8',
 '8',
 '8',
 '8',
 '8',
 '8',
 '8',
 '8',
 '8',
 '8',
 '8',
 '8',
 '8',
 '8',
 '8',
 '8',
 '8',
 '8',
 '8',
 '8',
 '8',
 ...]

In [0]:
#temp=67635
#tl=[]
#biglist=[]
#i=0
#for j in range(67635,89063):
#  temp=itemlist[i][2:]+itemlist[i+1][3:263]+itemlist[i+2][3:263]+itemlist[i+3][3:263]+itemlist[i+4][3:263]+itemlist[i+5][3:263]+itemlist[i+6][3:263]+itemlist[i+7][3:263]+itemlist[i+8][3:263]+itemlist[i+9][3:263]+itemlist[i+10][3:263]+itemlist[i+11][3:263]+itemlist[i+12][3:263]+itemlist[i+13][3:263]
#  biglist.append(temp)
#  i=i+14

In [0]:
#len(itemlist[0])

256

In [0]:
#pred=[itemlist[i][2] for i in range(len(itemlist))]
#itemlist=pred
#tl=[]
#biglist=[]
##itemlist=newlist
#i=0
#bigpred=[]
#for j in range(67635,89063):
#  temp=itemlist[i]+itemlist[i+1]+itemlist[i+2]+itemlist[i+3]+itemlist[i+4]+itemlist[i+5]+itemlist[i+6]+itemlist[i+7]+itemlist[i+8]+itemlist[i+9]+itemlist[i+10]+itemlist[i+11]+itemlist[i+12]+itemlist[i+13]
#  biglist.append(temp)
#  i=i+14
#
#finalpred.to_csv('/content/drive/My Drive/BCI MNIST/yvar1.csv')
#

In [0]:
#finalpred.to_csv('/content/drive/My Drive/BCI MNIST/yvar1.csv')

In [0]:
print(len(itemlist))
len(index)

310464

310464

In [0]:
import pandas as pd
df=pd.DataFrame(itemlist).astype(float)
#thresh = len(df) * .1
#df.dropna(thresh = thresh, axis = 1, inplace = True)

In [0]:
#t=df.head(1000).mean()
df=df.fillna(0) #cannot remove data since dropping the rows with nan incur huge data losses, so replacing it with none.

In [13]:
df.head(5)

           0            1            2            3    ...  316  317  318  319
0  4395.384615  4382.564102  4377.435897  4387.179487  ...  0.0  0.0  0.0  0.0
1  4489.230769  4475.384615  4474.358974  4486.666666  ...  0.0  0.0  0.0  0.0
2  4538.461538  4528.717948  4524.615384  4526.153846  ...  0.0  0.0  0.0  0.0
3  4207.692307  4205.641025  4200.512820  4194.358974  ...  0.0  0.0  0.0  0.0
4  4497.948717  4498.461538  4494.871794  4497.948717  ...  0.0  0.0  0.0  0.0

[5 rows x 320 columns]

In [18]:
var=len(itemlist)
for i in range(14):
  if var%14==0:
    break
  var-=1

'8'

In [0]:
#combining data for same instances
itemlist=df.values.tolist()
tl=[]
biglist=[]
i=0
bigpred=[]
index=index[:var]
itemlist=itemlist[:var]
for j in range(0,var,14):
  temp=itemlist[i]+itemlist[i+1]+itemlist[i+2]+itemlist[i+3]+itemlist[i+4]+itemlist[i+5]+itemlist[i+6]+itemlist[i+7]+itemlist[i+8]+itemlist[i+9]+itemlist[i+10]+itemlist[i+11]+itemlist[i+12]+itemlist[i+13]
  temppred=index[i]+index[i+1]+index[i+2]+index[i+3]+index[i+4]+index[i+5]+index[i+6]+index[i+7]+index[i+8]+index[i+9]+index[i+10]+index[i+11]+index[i+12]+index[i+13]
  biglist.append(temp)
  bigpred.append(temppred)
  i=i+14

In [20]:
len(biglist)

21428

In [0]:
#(creating data frames)
finaldf=pd.DataFrame(biglist) 
finalpred=pd.DataFrame(bigpred)

In [22]:
len(finaldf)==len(finalpred)

True

In [0]:
#saving dataframesss
finaldf.to_csv('/content/drive/My Drive/BCI MNIST/xpadvar3.csv')
finalpred.to_csv('/content/drive/My Drive/BCI MNIST/ypadvar3.csv')

In [24]:
finaldf.head(5)

          0            1            2            3     ...  4476  4477  4478  4479
0  4395.384615  4382.564102  4377.435897  4387.179487  ...   0.0   0.0   0.0   0.0
1  4385.641025  4381.538461  4386.666666  4383.589743  ...   0.0   0.0   0.0   0.0
2  4380.512820  4389.743589  4395.897435  4395.384615  ...   0.0   0.0   0.0   0.0
3  4395.897435  4390.769230  4403.589743  4411.282051  ...   0.0   0.0   0.0   0.0
4  4395.384615  4385.128205  4382.051282  4390.769230  ...   0.0   0.0   0.0   0.0

[5 rows x 4480 columns]